apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meureplicaset
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-web
          image: williameliasalves/desafio_backend:latest
          ports:
            - containerPort: 8080
  replicas: 4
